import { Catalog, Group, Control, Profile, SystemSecurityPlan, ComponentDefinition, AssessmentPlan, AssessmentResults, PlanOfActionAndMilestones, MappingCollection, OscalDocument } from './types/oscal';

export const STAGE_CANONICAL_ROUTES: Record<string, string> = {
  catalogs: 'catalogs',
  catalog: 'catalogs',
  profiles: 'profiles',
  profile: 'profiles',
  ssps: 'ssps',
  ssp: 'ssps',
  'system-security-plan': 'ssps',
  'system-security-plans': 'ssps',
  'component-definitions': 'component-definitions',
  'component-definition': 'component-definitions',
  components: 'component-definitions',
  component: 'component-definitions',
  'assessment-plans': 'assessment-plans',
  'assessment-plan': 'assessment-plans',
  'assessment-results': 'assessment-results',
  'assessment-result': 'assessment-results',
  poams: 'poams',
  poam: 'poams',
  'plan-of-action-and-milestones': 'poams',
  'control-mappings': 'control-mappings',
  'control-mapping': 'control-mappings',
  'mapping-collections': 'control-mappings',
  'mapping-collection': 'control-mappings',
  mappings: 'control-mappings',
  mapping: 'control-mappings',
};

export const ROOT_KEYS: Record<string, string> = {
  catalogs: 'catalog',
  catalog: 'catalog',
  profiles: 'profile',
  profile: 'profile',
  ssps: 'system-security-plan',
  ssp: 'system-security-plan',
  'system-security-plan': 'system-security-plan',
  'system-security-plans': 'system-security-plan',
  'component-definitions': 'component-definition',
  'component-definition': 'component-definition',
  components: 'component-definition',
  component: 'component-definition',
  'assessment-plans': 'assessment-plan',
  'assessment-plan': 'assessment-plan',
  'assessment-results': 'assessment-results',
  'assessment-result': 'assessment-results',
  poams: 'plan-of-action-and-milestones',
  poam: 'plan-of-action-and-milestones',
  'plan-of-action-and-milestones': 'plan-of-action-and-milestones',
  'control-mappings': 'mapping-collection',
  'control-mapping': 'mapping-collection',
  'mapping-collections': 'mapping-collection',
  'mapping-collection': 'mapping-collection',
  mappings: 'mapping-collection',
  mapping: 'mapping-collection',
};

export const STAGE_LABELS: Record<string, string> = {
  catalogs: 'Catalog',
  catalog: 'Catalog',
  profiles: 'Profile',
  profile: 'Profile',
  ssps: 'System Security Plan',
  ssp: 'System Security Plan',
  'component-definitions': 'Component Definition',
  'component-definition': 'Component Definition',
  components: 'Component Definition',
  component: 'Component Definition',
  'assessment-plans': 'Assessment Plan',
  'assessment-plan': 'Assessment Plan',
  'assessment-results': 'Assessment Results',
  'assessment-result': 'Assessment Results',
  poams: 'POA&M',
  poam: 'POA&M',
  'control-mappings': 'Control Mapping',
  'control-mapping': 'Control Mapping',
  'mapping-collections': 'Control Mapping',
  'mapping-collection': 'Control Mapping',
  mappings: 'Control Mapping',
  mapping: 'Control Mapping',
};

export const STAGE_ICONS: Record<string, string> = {
  catalogs: '📖',
  catalog: '📖',
  profiles: '⚙️',
  profile: '⚙️',
  ssps: '📋',
  ssp: '📋',
  'component-definitions': '🧱',
  'component-definition': '🧱',
  components: '🧱',
  component: '🧱',
  'assessment-plans': '📅',
  'assessment-plan': '📅',
  'assessment-results': '✅',
  'assessment-result': '✅',
  poams: '⚠️',
  poam: '⚠️',
  'control-mappings': '🔗',
  'control-mapping': '🔗',
  'mapping-collections': '🔗',
  'mapping-collection': '🔗',
  mappings: '🔗',
  mapping: '🔗',
};

export const STAGE_TO_MODEL: Record<string, string> = {
  catalogs: 'catalog',
  catalog: 'catalog',
  profiles: 'profile',
  profile: 'profile',
  ssps: 'ssp',
  ssp: 'ssp',
  'component-definitions': 'component-definition',
  'component-definition': 'component-definition',
  components: 'component-definition',
  component: 'component-definition',
  'assessment-plans': 'assessment-plan',
  'assessment-plan': 'assessment-plan',
  'assessment-results': 'assessment-results',
  'assessment-result': 'assessment-results',
  poams: 'poam',
  poam: 'poam',
  'control-mappings': 'control-mappings',
  'control-mapping': 'control-mappings',
  'mapping-collections': 'control-mappings',
  'mapping-collection': 'control-mappings',
  mappings: 'control-mappings',
  mapping: 'control-mappings',
};

export const OSCAL_DEFINED_COMPONENT_TYPES = [
  'interconnection',
  'software',
  'hardware',
  'service',
  'policy',
  'physical',
  'process-procedure',
  'plan',
  'guidance',
  'standard',
  'validation',
  'region',
  'zone',
  'resource-container',
  'network'
] as const;

export type OscalDefinedComponentType = typeof OSCAL_DEFINED_COMPONENT_TYPES[number];

export const STAGE_CONFIG: Record<string, unknown> = {
  catalogs: {
    rootKey: 'catalog',
    label: 'Catalog',
    extraFields: [
      { key: 'groups', label: 'Groups (JSON array)', type: 'json', placeholder: '[]', required: false },
    ],
  },
  profiles: {
    rootKey: 'profile',
    label: 'Profile',
    extraFields: [
      { key: 'imports', label: 'Imports (JSON array)', type: 'json', placeholder: '[{"href": "catalog-uuid-here"}]', required: true },
      { key: 'merge', label: 'Merge (JSON object)', type: 'json', placeholder: '{}', required: false },
      { key: 'modify', label: 'Modify (JSON object)', type: 'json', placeholder: '{}', required: false },
      { key: 'local-controls', label: 'Local Controls (JSON array)', type: 'json', placeholder: '[]', required: false },
    ],
  },
  ssps: {
    rootKey: 'system-security-plan',
    label: 'System Security Plan',
    extraFields: [
      { key: 'import-profile', label: 'Import Profile (JSON: {"href":"..."})', type: 'json', placeholder: '{"href": "profile-uuid-here"}', required: true },
      { key: 'system-characteristics', label: 'System Characteristics (JSON)', type: 'json', placeholder: '{"system-name": "My System", "description": "..."}', required: false },
      { key: 'control-implementation', label: 'Control Implementation (JSON)', type: 'json', placeholder: '{"implemented-requirements": []}', required: false },
    ],
  },
  'component-definitions': {
    rootKey: 'component-definition',
    label: 'Component Definition',
    extraFields: [
      { key: 'components', label: 'Components (JSON array)', type: 'json', placeholder: '[]', required: false },
      { key: 'capabilities', label: 'Capabilities (JSON array)', type: 'json', placeholder: '[]', required: false },
      { key: 'import-component-definitions', label: 'Import Component Definitions (JSON array)', type: 'json', placeholder: '[]', required: false },
    ],
  },
  'assessment-plans': {
    rootKey: 'assessment-plan',
    label: 'Assessment Plan',
    extraFields: [
      { key: 'import-ssp', label: 'Import SSP (JSON: {"href":"..."})', type: 'json', placeholder: '{"href": "ssp-uuid-here"}', required: false },
      { key: 'tasks', label: 'Tasks (JSON array)', type: 'json', placeholder: '[]', required: false },
    ],
  },
  'assessment-results': {
    rootKey: 'assessment-results',
    label: 'Assessment Results',
    extraFields: [
      { key: 'import-ap', label: 'Import Assessment Plan (JSON: {"href":"..."})', type: 'json', placeholder: '{"href": "ap-uuid-here"}', required: false },
      { key: 'results', label: 'Results (JSON array)', type: 'json', placeholder: '[]', required: false },
    ],
  },
  poams: {
    rootKey: 'plan-of-action-and-milestones',
    label: 'POA&M',
    extraFields: [
      { key: 'poam-items', label: 'POA&M Items (JSON array)', type: 'json', placeholder: '[]', required: false },
    ],
  },
  'control-mappings': {
    rootKey: 'mapping-collection',
    label: 'Control Mapping',
    extraFields: [
      { key: 'provenance', label: 'Provenance (JSON)', type: 'json', placeholder: '{"method": "human", "matching-rationale": "syntactic", "status": "draft", "mapping-description": "NIST to ISO control crosswalk"}', required: false },
      { key: 'mappings', label: 'Mappings (JSON array)', type: 'json', placeholder: '[]', required: false },
    ],
  },
};
